---
title: "Draft code for calculating and visualizing duckweed growth (experimental data)"
author: "Debora"
date: "10/14/2021"
output: github_document
---

### Download dataset from github repository and check import
```{r}
duckweed <- read.csv("https://raw.githubusercontent.com//Cuddington-Lab/thermal-experiments/main/Aphid_Data - Sheet1.csv",
                  header=TRUE, stringsAsFactors = TRUE)
str(duckweed)
```

### Perform data cleaning
```{r}
# Select constant temperatures only
duckweed_constant <- duckweed[duckweed$Autocorrelation == "constant",]

# Remove NA data
duckweed_constant <- na.omit(duckweed_constant)

# Remove observations for which incubators had issues
duckweed_constant <- duckweed_constant[!grepl("Celsius|celsius|Computer", duckweed_constant$Notes),]
```

### Perform data manipulations
```{r}
# Create new column including sum of fronds
duckweed_constant$Total_frond <- duckweed_constant$Duckweed_Rep1 + 
  duckweed_constant$Duckweed_Rep2 + duckweed_constant$Duckweed_Rep3
```

### Scatterplot
```{r}
plot(duckweed_constant$Mean_Temp, duckweed_constant$Total_frond,
    pch=19, xlab="Temperature (ºC)", ylab="Total Frond Count",
    main="Duckweed frond counts across constant temperatures")
```

### Relative growth rate calculation

### Relative growth rate equation
$$ RGR = ((log(Nf)-log(Ni))/t) $$
### Where Nf = final frond count, Ni = initial frond count, t = growth time in days

# Calculate RGR, mean, and SD
```{r}
duckweed_constant$RGR <- (log(duckweed_constant$Total_frond) - log(12)) / 5

stats <- data.frame(group=levels(factor(duckweed_constant$Mean_Temp)),
                               mean=(aggregate(duckweed_constant$RGR,
                               by=list(duckweed_constant$Mean_Temp),
                               FUN=mean)$x),sd=(aggregate(duckweed_constant$RGR,
                               by=list(duckweed_constant$Mean_Temp),
                               FUN=sd)$x)
                               )
stats <- transform(stats, group = as.numeric(group))
```

### Relative growth rate visualization with error bars
```{r}
plot(stats$group, stats$mean,
    ylim=range(c(stats$mean-stats$sd,
                 stats$mean+stats$sd)),
    pch=19, xlab="Temperature (ºC)", ylab="Mean relative growth rate +/- SD",
    main="Duckweed relative growth rate across constant temperatures"
    )

arrows(x0=stats$group, y0=stats$mean-stats$sd, x1=stats$group, y1=stats$mean+stats$sd, code=3, angle=90, length=0.1)
```
