---
title: "Comparing_common_duckweed_strains"
author: "Debora"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rTPC)
library(nls.multstart)
library(lme4)
library(emmeans)

# Load data
datin1 <- read.csv("https://raw.githubusercontent.com/Cuddington-Lab/thermal-experiments/main/dataset_autocorrelation_2022-2023.csv",
                   header=TRUE, stringsAsFactors = TRUE, fileEncoding="UTF-8-BOM")
datin2 <- read.csv("https://raw.githubusercontent.com/Cuddington-Lab/thermal-experiments/main/dataset_autocorrelation_2021-2022.csv",
                   header=TRUE, stringsAsFactors = TRUE, fileEncoding="UTF-8-BOM")
datin <- rbind(datin1, datin2)

# Total reproductive number for each replicate (summing 3 dishes)
datin$Frond_count <- datin$Frond_count_1 + datin$Frond_count_2 + datin$Frond_count_3

# Selecting constant temperature experiments and removing failed ones
datin <- subset(datin, Treatment == "constant")
datin <- subset(datin, (!Errors == "y") | is.na(Errors))
datin <- subset(datin, !Species == "LP")

# Plotting observations
colors <- c("#999999", "#E69F00")
plot(jitter(datin$Mean_temperature, 3), datin$Frond_count, pch = 19, col = colors[factor(datin$Species)])
legend(6, 68, legend=c("Field_LM", "Lab_LM"), col=colors, pch=16, cex=0.8)

# Exclude outlier
datin <- datin[!(datin$Mean_temperature == 20 & datin$Frond_count > 50), ]

# Model thermal performance via Ratkowsky curve
tpc <- data.frame(temp = datin$Mean_temperature, frond = datin$Frond_count, Species = datin$Species)
mylist <- list()
mylist[[1]] <- subset(tpc, Species == "Field_LM")
mylist[[2]] <- subset(tpc, Species == "Lab_LM")

mod <- "ratkowsky_1983"
new_data <- data.frame(temp = seq(min(datin$Mean_temperature), max(datin$Mean_temperature), 0.5))
all_results <- list()
count <- 1

for (i in mylist){
  start_vals <- get_start_vals(i[, 1], i[, 2], model_name = mod)
  low_lims <- get_lower_lims(i[, 1], i[, 2], model_name = mod)
  upper_lims <- get_upper_lims(i[, 1], i[, 2], model_name = mod)

  fit <- nls_multstart(frond ~ ratkowsky_1983(temp = temp, tmin, tmax, a, b),
                       data = i[, 1:2],
                       iter = 500,
                       start_lower = start_vals - 10,
                       start_upper = start_vals + 10,
                       lower = low_lims,
                       upper = upper_lims,
                       supp_errors = 'Y')

  result <- predict(fit, newdata = new_data)
  all_results[[count]] <- as.data.frame(result)
  count <- count + 1
}

df <- as.data.frame(do.call(cbind, all_results))
colnames(df) <- c("tpc_fieldLM", "tpc_labLM")
df$temp <- new_data$temp

plot(jitter(datin$Mean_temperature, 3), datin$Frond_count, pch = 19, 
     cex=1.3, cex.lab=1.4, cex.axis=1.4, cex.main=1.4, cex.sub=1.4,
     col = colors[factor(datin$Species)], xlab = "Temperature", ylab = "Reproduction (# of individuals)")
legend(6, 55, legend=c("L. minor (field)", "L. minor (lab)"), text.font=c(3,3),
       col=colors, pch=16, cex=1.1)
lines(df$temp, df$tpc_fieldLM, col = "#999999", lwd = 3)
lines(df$temp, df$tpc_labLM, col = "orange", lwd = 3)


# Remove treatments with less than 3 observations
tab <- table(datin$Mean_temperature, datin$Species)
valid_temps <- rownames(tab)[rowSums(tab >= 3) == 2]
tpc_model <- datin[datin$Mean_temperature %in% valid_temps, ]

tpc_model$Mean_temperature <- as.factor(tpc_model$Mean_temperature)

# Fit GLM and do pairwise comparisons
simple <- glm(Frond_count ~ Mean_temperature * Species, data = tpc_model, family = "quasipoisson")
phi <- sum(residuals(simple, type = "pearson")^2) / df.residual(simple)
pairwise_adj <- emmeans(simple, pairwise ~ Species | Mean_temperature, type = "response", vcov. = vcov(simple) * phi)

pairwise_adj
```
