---
title: "preliminary_analyses_blending_groups"
author: "Debora"
date: "2025-06-16"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Data Grouping and Exclusion Rationale
The following groups were combined because there were no significant differences between them:

- 10°C and 15°C temperature treatments
  
- Lemna minor strains from a US lab and field collection
  
- Preparation methods with and without repeated first-daughter separation

```{r}
library(lme4)
library(performance)
library(sjPlot)

## Testing for differences in preparation methods, average temperatures,
## and strains to justify merging of groups performed during data analysis

### This dataset contains replicates for which a preparation technique was performed (repeated first born frond selection to reduce maternal effects)
original_dataset_2 <- read.csv("https://raw.githubusercontent.com/Cuddington-Lab/thermal-experiments/main/dataset_autocorrelation_2022-2023.csv",header=TRUE, stringsAsFactors = TRUE,fileEncoding="UTF-8-BOM")
original_dataset_2$prep <- rep("yes",times=length(original_dataset_2$Experiment_Number))

### This dataset contains replicates of experiments performed without a preparation technique 
original_dataset_1 <- read.csv("https://raw.githubusercontent.com/Cuddington-Lab/thermal-experiments/main/dataset_autocorrelation_2021-2022.csv",header=TRUE, stringsAsFactors = TRUE,fileEncoding="UTF-8-BOM")
original_dataset_1$prep <- rep("no",times=length(original_dataset_1$Experiment_Number))

datin <- rbind(original_dataset_1,original_dataset_2)

datin <- datin[!(datin$Treatment == 0 & (datin$Obs_sd <= 2.1 | datin$Obs_sd >= 2.9))
               &!(datin$Treatment == 0.95 & (datin$Obs_sd <= 2.1 | datin$Obs_sd >= 2.9)),]

datin <- datin[!(datin$Treatment == 0 & (datin$Obs_ac <= -0.2 | datin$Obs_ac >= 0.2))
               &!(datin$Treatment == 0.95 & (datin$Obs_ac <= 0.92 | datin$Obs_ac >= 0.98)),]

datin <- subset(datin, !Errors == "y"|is.na(Errors))
datin <- subset(datin, !Treatment == "constant")

colnames(datin)[6] <- "Label"
table(datin$Label, datin$cat_1)
levels(datin$cat_1) = c("no autocorrelation","hot-cold","no autocorrelation","cold-hot")
datin$Treatment<-paste0(datin$cat_1)

### Relabel groups to simplify visualization of results
library(stringr)
datin$Label <- str_replace(datin$Label, "0.95", "strong autocorrelation")
datin$Label <- str_replace(datin$Label, "0", "no autocorrelation")

datin$Exp_run <- str_sub(datin$Profile_name,-2,-1)
datin$Exp_run <- gsub('_','',datin$Exp_run)
datin$Exp_run <- as.numeric(datin$Exp_run)

# Subset data to keep only those Exp_run that have at least 3 occurrences within each Mean_Temperature
datin <- datin[
  ave(seq_along(datin$Exp_run), 
      interaction(datin$Exp_run, datin$Mean_temperature, datin$Species), 
      FUN = length) >= 3, 
]

datin$total_living_fronds <- (datin$Frond_count_1 + datin$Frond_count_2 + datin$Frond_count_3)

# Datasets and variables to iterate over
datin1015 <- subset(datin, (Species == "Lab_LM" | Species == "Field_LM") &
                      (Mean_temperature == 10 | Mean_temperature == 15))

datasets <- list(datin1015 = datin1015)

predictors_list <- list(
  datin1015 = c("Mean_temperature*Treatment", "prep*Treatment")
)

# Initialize lists to save results
best_models <- list()
model_diagnostics <- list()

# Loop over datasets and predictors
for (data_name in names(datasets)) {
  data <- datasets[[data_name]]
  predictors <- predictors_list[[data_name]]
  
  for (pred in predictors) {
    # Fit models
    simple <- glm(as.formula(paste("total_living_fronds ~", pred)), data = data, family="poisson")
    exp_number <- glmer(as.formula(paste("total_living_fronds ~", pred, "+ (1|Exp_run)")), data = data, family="poisson")
    
    # Store candidate models
    Cand.modsF <- list("no random effects" = simple, 
                       "experiment number" = exp_number)
    
    # Compare models
    compareF <- compare_performance(Cand.modsF)
    
    # Select best model and save it
    best_model_index <- which.min(compareF$AIC)
    best_model <- Cand.modsF[[best_model_index]]
    
    # Save best model and its diagnostics
    best_models[[paste(data_name, pred)]] <- best_model
}}

#at 10-15C, no differences between average temperature and preparation method
summary(best_models[[1]])
summary(best_models[[2]])

#at 10-15C, no differences between duckweed strains (lab and field LM)
exp_number <- glmer(total_living_fronds ~ Species * Treatment + (1|Exp_run), data = datin1015, family="poisson")
simple <- glm(total_living_fronds ~ Species * Treatment, data = datin1015, family="poisson")
tab_model(simple)
```

