---
title: "Autocorrelation_stats"
author: "Debora"
date: "`r Sys.Date()`"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

## Load datasets
```{r}
# This dataset contains replicates for which a preparation technique was performed (repeated first born frond selection to reduce maternal effects)
original_dataset_2 <- read.csv("https://raw.githubusercontent.com/Cuddington-Lab/thermal-experiments/main/dataset_autocorrelation_2022-2023.csv",header=TRUE, stringsAsFactors = TRUE,fileEncoding="UTF-8-BOM")
original_dataset_2$prep <- rep("yes",times=length(original_dataset_2$Experiment_Number))

# This dataset contains replicates of experiments performed without a preparation technique 
original_dataset_1 <- read.csv("https://raw.githubusercontent.com/Cuddington-Lab/thermal-experiments/main/dataset_autocorrelation_2021-2022.csv",header=TRUE, stringsAsFactors = TRUE,fileEncoding="UTF-8-BOM")
original_dataset_1$prep <- rep("no",times=length(original_dataset_1$Experiment_Number))
```

Clean the data according to pre-defined thresholds (temperature data quality check)

```{r}
# Blending both datasets, as there are no significant differences between preparation methods (probably because we only have 2 methods in low temperatures)
datin <- rbind(original_dataset_1,original_dataset_2)

datin <- datin[!(datin$Treatment == 0 & (datin$Obs_sd <= 2.1 | datin$Obs_sd >= 2.9))
               &!(datin$Treatment == 0.95 & (datin$Obs_sd <= 2.1 | datin$Obs_sd >= 2.9)),]

datin <- datin[!(datin$Treatment == 0 & (datin$Obs_ac <= -0.2 | datin$Obs_ac >= 0.2))
               &!(datin$Treatment == 0.95 & (datin$Obs_ac <= 0.92 | datin$Obs_ac >= 0.98)),]

datin <- subset(datin, !Errors == "y"|is.na(Errors))
datin <- subset(datin, !Treatment == "constant")
```


```{r include=FALSE}
## Data Relabeling
# We relabel the groups for easier visualization and manipulate the dataset to  prepare it for analysis.

colnames(datin)[6] <- "Label"
table(datin$Label, datin$cat_1)
levels(datin$cat_1) = c("no autocorrelation","hot-cold","no autocorrelation","cold-hot")
datin$Treatment<-paste0(datin$cat_1)

# Relabel groups to further simplify visualization of results
library(stringr)
datin$Label <- str_replace(datin$Label, "0.95", "strong autocorrelation")
datin$Label <- str_replace(datin$Label, "0", "no autocorrelation")

# Extract experiment run IDs
datin$Exp_run <- str_sub(datin$Profile_name,-2,-1)
datin$Exp_run <- gsub('_','',datin$Exp_run)
datin$Exp_run <- as.numeric(datin$Exp_run)
```


```{r include=FALSE}
## Further Data Processing

# Blending 10C and 15C, as there are no significant differences between performance in these 2 average temperatures
datin$Mean_temperature <- str_replace(datin$Mean_temperature, "15", "10")
datin$Mean_temperature <- str_replace(datin$Mean_temperature, "10", "10-15")

# Removing "lab" strain, as preliminary statistical analyses showed significant differences between the 2 common duckweed strains used in this experiment in average temperature of 27C
datin <- subset(datin, !(Species == "Lab_LM" & Mean_temperature == "27"))

# Blending common duckweed strains, as preliminary analyses showed no differences between them
datin$Species <- gsub("Lab_LM|Field_LM", "LM", datin$Species)
```



```{r echo=FALSE}
## View dataset and response variable (number of living fronds)
datin$change_frond_count <- (datin$Frond_count_1 + datin$Frond_count_2 + datin$Frond_count_3)-12
datin$total_living_fronds <- (datin$Frond_count_1 + datin$Frond_count_2 + datin$Frond_count_3)

datin <- within(datin, Mean_temperature <- relevel(factor(Mean_temperature), ref = "10-15"))
datin <- within(datin, Treatment <- relevel(factor(Treatment), ref = "no autocorrelation"))
datin <- within(datin, Species <- relevel(factor(Species), ref = "LM"))

datin$Experiment_Number <- as.factor(datin$Experiment_Number)
datin$Incubator <- as.factor(datin$Incubator)
datin$Mean_temperature <- as.factor(datin$Mean_temperature)
datin$Treatment <- as.factor(datin$Treatment)
```

```{r include=FALSE}
datin <- subset(datin,Species=="LM")

datin$r <- datin$total_living_fronds

knitr::kable(head(datin[, c(34, 33, 36, 37)]))
ave<-mean(datin$r[datin$Label=="strong autocorrelation" & datin$Mean_temperature=="37"])
ave
# Percents for the results section
length(datin$r[datin$Treatment=="hot-cold" & datin$Mean_temperature=="37" & datin$r<ave])/length(datin$r[datin$Treatment=="hot-cold" & datin$Mean_temperature=="37"])*100

length(datin$r[datin$Treatment=="cold-hot" & datin$Mean_temperature=="37" & datin$r<ave])/length(datin$r[datin$Treatment=="cold-hot" & datin$Mean_temperature=="37"])*100
```

## Plotting histograms
```{r echo=FALSE, message=FALSE, warning=FALSE, margin=0}
library(scales)
library(ggpubr)
library(ggplot2)
library(patchwork)


# Plot 1: 10-15°C, No Autocorrelation
plot10no <- ggplot(subset(datin, datin$Mean_temperature == "10-15" & datin$Label == "no autocorrelation"), 
                   aes(x = r)) + 
  geom_histogram(colour = "#999999", fill = "#999999", bins = 10) + 
  theme_bw(base_size = 16) + 
  scale_x_continuous() +
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, by = 2)) + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), legend.position = "none") + 
  xlab("Number of living fronds") + 
  ylab("")

# Plot 2: 10-15°C, Strong Autocorrelation
plot10strong <- ggplot(subset(datin, datin$Mean_temperature == "10-15" & datin$Label == "strong autocorrelation"), 
                       aes(x = r)) + 
  geom_histogram(colour = "#999999", fill = "#999999", bins = 10) + 
  theme_bw(base_size = 16) + 
  scale_x_continuous() +
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, by = 2)) + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), legend.position = "none") + 
  geom_jitter(data = subset(datin, datin$Mean_temperature == "10-15" & datin$Label == "strong autocorrelation"), 
              aes(x = r, y = 0.5, col = Treatment), size = 5) + 
  scale_color_manual(values = c("#0072B2", "#D55E00")) + 
  xlab("Number of living fronds") + 
  ylab("")

# Plot 3: 27°C, No Autocorrelation
plot27no <- ggplot(subset(datin, datin$Mean_temperature == "27" & datin$Label == "no autocorrelation"), 
                   aes(x = r)) + 
  geom_histogram(colour = "#999999", fill = "#999999", bins = 10) + 
  theme_bw(base_size = 16) + 
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, by = 2)) + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), legend.position = "none") + 
  xlab("Number of living fronds") + 
  ylab("")

# Plot 4: 27°C, Strong Autocorrelation
plot27strong <- ggplot(subset(datin, datin$Mean_temperature == "27" & datin$Label == "strong autocorrelation"), 
                       aes(x = r)) + 
  geom_histogram(colour = "#999999", fill = "#999999", bins = 10) + 
  theme_bw(base_size = 16) + 
  #scale_x_continuous(limits = c(0.2, 0.45), breaks = seq(0, 0.45, by = 0.05)) +
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, by = 2)) + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), legend.position = "none") + 
  geom_jitter(data = subset(datin, datin$Mean_temperature == "27" & datin$Label == "strong autocorrelation"), 
              aes(x = r, y = 0.5, col = Treatment), size = 5) + 
  scale_color_manual(values = c("#0072B2", "#D55E00")) + 
  xlab("Number of living fronds") + 
  ylab("")

# Plot 5: 37°C, No Autocorrelation
plot37no <- ggplot(subset(datin, datin$Mean_temperature == "37" & datin$Label == "no autocorrelation"), 
                   aes(x = r)) + 
  geom_histogram(colour = "#999999", fill = "#999999", bins = 5) + 
  theme_bw(base_size = 16) + 
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, by = 2)) + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), legend.position = "none") + 
  xlab("Number of living fronds") + 
  ylab("")

# Plot 6: 37°C, Strong Autocorrelation
plot37strong <- ggplot(subset(datin, datin$Mean_temperature == "37" & datin$Label == "strong autocorrelation"), 
                       aes(x = r)) + 
  geom_histogram(colour = "#999999", fill = "#999999", bins = 10) + 
  theme_bw(base_size = 16) + 
  scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, by = 2)) + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
        axis.line = element_line(colour = "black"), legend.position = "none") + 
  geom_jitter(data = subset(datin, datin$Mean_temperature == "37" & datin$Label == "strong autocorrelation"), 
              aes(x = r, y = 0.5, col = Treatment), size = 5) + 
  scale_color_manual(values = c("#0072B2", "#D55E00")) + 
  xlab("Number of living fronds") + 
  ylab("")

# Combine the plots
patchwork <- plot10no + plot10strong + plot27no + plot27strong + plot37no + plot37strong

patchwork + 
  plot_layout(ncol = 2, tag_level = 'new', axis_titles = "collect", widths = c(0.5, 0.5, 0.5), heights = unit(c(1, 1, 1), c('null', 'null', 'null'))) + 
  plot_annotation(title = 'Frequency distribution of performance across average temperatures and autocorrelation strength', 
                  subtitle = '                  No autocorrelation                       Strong autocorrelation', 
                  tag_levels = list(c('10-15\u00B0C','', '27\u00B0C','','37\u00B0C',''), 
                                    c('control','strong autocorrelation'))) & 
  theme(plot.tag = element_text(size = 12), plot.title = element_text(size = 18), 
        plot.subtitle = element_text(size = 16))


```



## Plotting histograms (stacked)
```{r echo=FALSE, message=FALSE, warning=FALSE, margin=0}
library(scales)
library(ggpubr)
library(ggplot2)
library(patchwork)

# Define global x-axis limits across all Mean_temperature groups
x_limits_global <- range(datin$r, na.rm = TRUE)

# Function to create histograms with a shared x-axis
create_histogram <- function(data, temp, label) {
  ggplot(subset(data, Mean_temperature == temp & Label == label), 
         aes(x = r, fill = Treatment)) + 
    geom_histogram(colour = "#999999", bins = 10, position = "identity", alpha = 0.50) + 
    theme_bw(base_size = 16) + 
    scale_x_continuous(limits = c(NA, NA), expand = expansion(mult = 0.05)) +  # Ensure no data is removed
    scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, by = 2)) + 
    theme(panel.border = element_blank(), panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
          axis.line = element_line(colour = "black"), legend.position = "none") + 
    scale_fill_manual(values = c("#0072B2", "#D55E0080")) + 
    xlab("Number of living fronds") + 
    ylab("")
}

# Generate plots
plot10no <- create_histogram(datin, "10-15", "no autocorrelation")
plot10strong <- create_histogram(datin, "10-15", "strong autocorrelation")
plot27no <- create_histogram(datin, "27", "no autocorrelation")
plot27strong <- create_histogram(datin, "27", "strong autocorrelation")
plot37no <- create_histogram(datin, "37", "no autocorrelation")
plot37strong <- create_histogram(datin, "37", "strong autocorrelation")

# Combine the plots
patchwork <- plot10no + plot10strong + plot27no + plot27strong + plot37no + plot37strong

patchwork + 
  plot_layout(ncol = 2, tag_level = 'new', axis_titles = "collect", widths = c(0.5, 0.5, 0.5), heights = unit(c(1, 1, 1), c('null', 'null', 'null'))) + 
  plot_annotation(title = 'Frequency distribution of performance across average temperatures and autocorrelation strength', 
                  subtitle = '                  No autocorrelation                       Strong autocorrelation', 
                  tag_levels = list(c('10-15\u00B0C','', '27\u00B0C','','37\u00B0C',''), 
                                    c('control','strong autocorrelation'))) & 
  theme(plot.tag = element_text(size = 12), plot.title = element_text(size = 18), 
        plot.subtitle = element_text(size = 14))
```
